routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::post('/winning-number', 'WinningNumberController@store')->name('winning-number.store');

Auth::routes();

Route::view('/admin/login', 'auth.admin.login');
Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login');
Route::post('/admin/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:Admin']], function(){
    Route::name('lucky-draw.')->group(function() {
        Route::get('/', 'LuckyDrawController@index')->name('index');
        Route::get('/lucky-draw/create', 'LuckyDrawController@create')->name('create');
        Route::post('/lucky-draw', 'LuckyDrawController@store')->name('store');
    });

    Route::name('prize.')->group(function() {
        Route::get('/prize', 'PrizeController@index')->name('index');
        Route::get('/prize/create', 'PrizeController@create')->name('create');
        Route::post('/prize', 'PrizeController@store')->name('store');
    });

    Route::get('winning-number', 'WinningNumberController@index')->name('winning-number.index');

    Route::get('user', 'Admin\CustomerController@index');
});

app/LuckyDraw.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LuckyDraw extends Model
{
    protected $guarded = [];

    public function prize()
    {
        return $this->belongsTo(Prize::class);
    }

    public function winningNumber()
    {
        return $this->belongsTo(WinningNumber::class);
    }

    public function winner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/LuckyDrawController.php
<?php

namespace App\Http\Controllers;

use App\LuckyDraw;
use App\Prize;
use App\WinningNumber;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class LuckyDrawController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $luckyDraws = LuckyDraw::latest()->get();

        return view('lucky-draw.index', compact('luckyDraws'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $prizes = Prize::all();

        return view('lucky-draw.create', compact('prizes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return void
     */
    public function store()
    {
        request()->validate([
            'prize' => 'required|integer|exists:prizes,id',
            'generate_randomly' => 'required|integer',
            'winning_number' => 'nullable|integer'
        ]);

        $prize = Prize::findOrFail(request('prize'));

        //total number of winners available
        $count = LuckyDraw::where('prize_id', $prize->id)
            ->count();

        //check if prize is available
        if($count === $prize->number_of_winners){
            return back()
                ->with('error', "There is no more winner slot for $prize->name");
        }

        //users who already won lucky draw
        $winners = LuckyDraw::whereDate('created_at', Carbon::today())
            ->get()
            ->pluck('user_id');

        if(request('generate_randomly')){
            if($prize->name === 'Grand Prize'){
                // get the highest winning numbers
                $highest = \DB::table('winning_numbers')
                    ->select('user_id', \DB::raw('count(user_id) as total'))
                    ->whereNotIn('user_id', $winners)
                    ->groupBy('user_id')
                    ->get()->max('total');

                // get users with highest winning numbers
                $highestWinningNumberUsers = \DB::table('winning_numbers')
                    ->select('user_id', \DB::raw('count(user_id) as total'))
                    ->whereNotIn('user_id', $winners)
                    ->groupBy('user_id')
                    ->having('total', $highest)
                    ->get()->pluck('user_id');

                $winningNumber = WinningNumber::whereIn('user_id', $highestWinningNumberUsers)
                    ->inRandomOrder()
                    ->limit(1)
                    ->first();
            }else{
                $winningNumber = WinningNumber::whereNotIn('user_id', $winners)
                    ->inRandomOrder()
                    ->limit(1)
                    ->first();
            }
        }else{
            $winningNumber = WinningNumber::whereNotIn('user_id', $winners)
                ->where('number', request('winning_number'))
                ->first();

            if(empty($winningNumber)){
                return back()
                    ->with('error', "User had won one of the lucky draw.");
            }
        }

        LuckyDraw::create([
            'winning_number_id' => $winningNumber->id,
            'user_id' => $winningNumber->user_id,
            'prize_id' => request('prize')
        ]);

        return redirect()->to(route('lucky-draw.index'))
            ->with('success', 'New Lucky draw has been created.');
    }
}

resources/views/lucky-draw/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="content-wrapper">
        <div class="col-md-8 col-md-offset-2">
            <section class="content-header">
                <h1>
                    Create new lucky draw
                </h1>
            </section>

            <section class="content">
                <div class="box box-primary">
                    <form action="{{route('lucky-draw.store')}}" method="POST" role="form">
                        @csrf
                        <div class="box-body">
                            <div class="form-group">
                                <label for="prize">Prize Types *</label>
                                <select name="prize" id="prize" class="form-control" required>
                                    <option value="" disabled selected>Please select</option>
                                    @foreach($prizes as $prize)
                                        <option value="{{$prize->id}}">{{$prize->name}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="generate_randomly">Generate Randomly</label>
                                <select name="generate_randomly" id="generate_randomly" class="form-control" required>
                                    <option value="" disabled selected>Please select</option>
                                    <option value=0>No</option>
                                    <option value=1>Yes</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="winning_number">Winning Number</label>
                                <input name="winning_number" type="number" class="form-control" id="winning_number" placeholder="Enter winning number...">
                            </div>
                        </div>

                        <div class="box-footer">
                            <a href="{{route('lucky-draw.index')}}" type="button" class="btn btn-primary">Back</a>
                            <button type="submit" class="btn btn-success">Create</button>
                        </div>

                        <div class="box-body">
                            @include('layouts._errors')
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/lucky-draw/index.blade.php
@extends('layouts.admin')

@section('extra-css')
    <link rel="stylesheet" href="{{asset('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
@endsection

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="col-md-6">
                    <h3>
                        Lucky Draw
                    </h3>
                </div>
                <div class="col-md-6" style="padding-top:12px">
                    <a href="{{route('lucky-draw.create')}}" class="pull-right btn btn-success btn-sm">
                        New Lucky Draw
                    </a>
                </div>
            </section>
            <section class="content">
                <div class="">
                    <div class="col-xs-12">
                        <div class="box">
                            <!-- /.box-header -->
                            <div class="box-body">
                                <table id="example2" class="table table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Date</th>
                                        <th>Prize</th>
                                        <th>Winning Number</th>
                                        <th>Winner</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($luckyDraws as $index => $luckyDraw)
                                        <tr>
                                            <td>{{++$index}}</td>
                                            <td>{{$luckyDraw->created_at->format('d M Y')}}</td>
                                            <td>{{$luckyDraw->prize->name}}</td>
                                            <td>{{$luckyDraw->winningNumber->number}}</td>
                                            <td>{{$luckyDraw->winner->name}}</td>
                                        </tr>
                                    @endforeach
                                </table>
                            </div>
                            <!-- /.box-body -->
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    @include('layouts._status')

@endsection

@section('extra-script')
    <script src="{{asset('bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    <script>
        $(function () {
            $('#example2').DataTable({
                'paging'      : true,
                'lengthChange': true,
                'searching'   : true,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false
            })
        })
    </script>
@endsection