routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::post('/winning-number', 'WinningNumberController@store')->name('winning-number.store');

Auth::routes();

Route::view('/admin/login', 'auth.admin.login');
Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login');
Route::post('/admin/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:Admin']], function(){
    Route::name('lucky-draw.')->group(function() {
        Route::get('/', 'LuckyDrawController@index')->name('index');
        Route::get('/lucky-draw/create', 'LuckyDrawController@create')->name('create');
        Route::post('/lucky-draw', 'LuckyDrawController@store')->name('store');
    });

    Route::name('prize.')->group(function() {
        Route::get('/prize', 'PrizeController@index')->name('index');
        Route::get('/prize/create', 'PrizeController@create')->name('create');
        Route::post('/prize', 'PrizeController@store')->name('store');
    });

    Route::get('winning-number', 'WinningNumberController@index')->name('winning-number.index');

    Route::get('user', 'Admin\CustomerController@index');
});

resources/views/layouts/admin/_footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
    </div>
    <strong>Copyright &copy; 2018 <a href="{{url('admin')}}">{{config('app.name')}}</a>.</strong> All rights
    reserved.
</footer>

resources/views/layouts/admin/_nav.blade.php
<header class="main-header">

    <!-- Logo -->
    <a href="index2.html" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>Admin</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Admin</b></span>
    </a>

    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="{{url('')}}" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="hidden-xs">Welcome back, {{Auth::user()->name}}</span>
                    </a>
                </li>
                <li class="dropdown user user-menu">
                    <a href="{{ url('admin/logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        Logout
                    </a>

                    <form id="logout-form" action="{{ url('admin/logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/admin/_sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            @role('Admin')
            <li>
                <a href="{{route('lucky-draw.index')}}"><i class="fa fa-dashboard"></i> <span>Lucky Draw</span></a>
            </li>
            <li>
                <a href="{{route('prize.index')}}"><i class="fa fa-dashboard"></i> <span>Prize</span></a>
            </li>
            <li>
                <a href="{{route('winning-number.index')}}"><i class="fa fa-dashboard"></i> <span>Winning Number</span></a>
            </li>
            <li>
                <a href="{{url('admin/user')}}"><i class="fa fa-user"></i> <span>User</span></a>
            </li>
            @endrole
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>