routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::post('/winning-number', 'WinningNumberController@store')->name('winning-number.store');

Auth::routes();

Route::view('/admin/login', 'auth.admin.login');
Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login');
Route::post('/admin/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:Admin']], function(){
    Route::name('lucky-draw.')->group(function() {
        Route::get('/', 'LuckyDrawController@index')->name('index');
        Route::get('/lucky-draw/create', 'LuckyDrawController@create')->name('create');
        Route::post('/lucky-draw', 'LuckyDrawController@store')->name('store');
    });

    Route::name('prize.')->group(function() {
        Route::get('/prize', 'PrizeController@index')->name('index');
        Route::get('/prize/create', 'PrizeController@create')->name('create');
        Route::post('/prize', 'PrizeController@store')->name('store');
    });

    Route::get('winning-number', 'WinningNumberController@index')->name('winning-number.index');

    Route::get('user', 'Admin\CustomerController@index');
});

app/Prize.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Prize extends Model
{
    protected $fillable = ['name', 'number_of_winners'];
}

app/Http/Controllers/PrizeController.php
<?php

namespace App\Http\Controllers;

use App\Prize;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class PrizeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $prizes = Prize::all();

        return view('prize.index', compact('prizes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('prize.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return void
     */
    public function store()
    {
        $data = request()->validate([
            'name' => 'required|string',
            'number_of_winners' => 'required|integer'
        ]);

        Prize::create($data);

        return redirect()->to(route('prize.index'))
            ->with('success', 'New Prize has been created.');
    }
}

resources/views/prize/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="content-wrapper">
        <div class="col-md-8 col-md-offset-2">
            <section class="content-header">
                <h1>
                    Create new prize
                </h1>
            </section>

            <section class="content">
                <div class="box box-primary">
                    <form action="{{route('prize.store')}}" method="POST" role="form">
                        @csrf
                        <div class="box-body">
                            <div class="form-group">
                                <label for="name">Prize Types *</label>
                                <input name="name" type="text" class="form-control" id="name" placeholder="Enter prize type">
                            </div>

                            <div class="form-group">
                                <label for="number_of_winners">Number of Winners</label>
                                <input name="number_of_winners" type="number" class="form-control" id="number_of_winners" placeholder="Enter winning number">
                            </div>
                        </div>

                        <div class="box-footer">
                            <a href="{{route('lucky-draw.index')}}" type="button" class="btn btn-primary">Back</a>
                            <button type="submit" class="btn btn-success">Create</button>
                        </div>

                        <div class="box-body">
                            @include('layouts._errors')
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/prize/index.blade.php
@extends('layouts.admin')

@section('extra-css')
    <link rel="stylesheet" href="{{asset('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
@endsection

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <section class="content-header">
                <div class="col-md-6">
                    <h3>
                        Prize
                    </h3>
                </div>
                <div class="col-md-6" style="padding-top:12px">
                    <a href="{{route('prize.create')}}" class="pull-right btn btn-success btn-sm">
                        New Prize
                    </a>
                </div>
            </section>
            <section class="content">
                <div class="">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-body">
                                <table id="example2" class="table table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Prize Type</th>
                                        <th>Number of Winners</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($prizes as $index => $prize)
                                        <tr>
                                            <td>{{++$index}}</td>
                                            <td>{{$prize->name}}</td>
                                            <td>{{$prize->number_of_winners}}</td>
                                        </tr>
                                    @endforeach
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    @include('layouts._status')
@endsection

@section('extra-script')
    <script src="{{asset('bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    <script>
        $(function () {
            $('#example2').DataTable({
                'paging'      : true,
                'lengthChange': true,
                'searching'   : true,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false
            })
        })
    </script>
@endsection